In [1]:
import cv2
import numpy as np

In [4]:
img = np.array([10, 8, -2, 0, 1,6,3,5,3,2,-4,11,7,-1,7,1]).reshape(4,4)
kernel = np.array([-2, 3, -1, 4, -1, 2, 0, 5, 3]).reshape(3,3)

In [5]:
kernel = np.array([0.077847, 0.123317, 0.077847, 0.123317, 0.195346, 0.123317, 0.077847, 0.123317, 0.077847]).reshape(3,3)

In [6]:
img

array([[10,  8, -2,  0],
       [ 1,  6,  3,  5],
       [ 3,  2, -4, 11],
       [ 7, -1,  7,  1]])

In [9]:
kernel

array([[0.077847, 0.123317, 0.077847],
       [0.123317, 0.195346, 0.123317],
       [0.077847, 0.123317, 0.077847]])

In [10]:
pad_img = np.pad(img, 1, mode = 'edge')
pad_img

array([[10, 10,  8, -2,  0,  0],
       [10, 10,  8, -2,  0,  0],
       [ 1,  1,  6,  3,  5,  5],
       [ 3,  3,  2, -4, 11, 11],
       [ 7,  7, -1,  7,  1,  1],
       [ 7,  7, -1,  7,  1,  1]])

In [13]:
img_top_left = 0
kernel_bottom_right = kernel.shape[1]
result = np.zeros((img.shape[0], img.shape[1]))
for row in range(0, img.shape[1]):
    for col in range(0, img.shape[1]):
        slices_img = pad_img[img_top_left+row : kernel_bottom_right+row, img_top_left+col:kernel_bottom_right+col]
        result[row][col] = element_wise_product(slices_img, kernel)
print(result)

[[7.475828 5.209906 2.198254 0.837033]
 [4.452167 3.443443 2.83741  3.708988]
 [3.20117  2.285206 2.911224 4.997479]
 [4.196811 2.66642  2.749384 3.829391]]


In [12]:
def element_wise_product(a, b ):
    return np.sum(a * b)